name: End-to-end tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install project dependencies
        run: yarn install

      - name: Build Next.js site
        run: yarn build

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          browser: chrome
          record: false
          wait-on: 'http://localhost:3000'
