name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      # You'll need to make sure node is installed first
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      # - name: Install yarn
      # run: npm install -g yarn
      - name: Install project dependencies
        run: yarn

      # Build the Next.js site
      - name: Build Next Site
        run: yarn build && yarn start

      # Run cypress tests
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          browser: chrome
          record: false
          wait-on: 'http://localhost:3000'
